format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$hg_branch\
$pijul_channel\
$package
$all\
${custom.tmux}\
"""

[hostname]
ssh_only = false
style = 'bold fg:172'

[directory]
style = 'bold fg:190'

[git_branch]
style = 'bold fg:141'

[git_status]
style = 'bold red'

[git_metrics]
disabled = false

[[battery.display]]
threshold = 20

[status]
disabled = true 

[docker_context]
format = '[via](dimmed) [$symbol$context]($style fg:61 dimmed) '

[bun]
format = '[via](dimmed) [$symbol($version)]($style dimmed) '

[nodejs]
format = 'via [$symbol($version)( but $engines_version is required)]($style) '
detect_files = ['package.json', '.node-version', '!bun.lockb', '!bunfig.toml']
 
[gcloud]
format = '[on](dimmed) [$symbol$active (\($project\))]($style fg:60 dimmed) '

[memory_usage]
disabled = false 
threshold = 85

[custom.tmux]
# only run inside tmux
when = """ [ -n "$TMUX" ] """
# rename tmux window to the repo’s basename; use dirname as fallback
command = '''
if top=$(git rev-parse --show-toplevel 2>/dev/null); then
  name=${top##*/}
else
  parent=${PWD%/*}
  name="${parent##*/}/${PWD##*/}"
fi
tmux rename-window "$name"
'''
# apparently if you set an empty string as format, the command does not run
format = "$output"
